import type { Product } from '@/types/product';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Wireless Headphones',
    description: 'Premium audio quality',
    sku: 'WH-2847',
    category: 'Audio',
    stock: 342,
    status: 'In Stock',
    image: '/images/products/wireless-headphones.jpg',
    totalQuantity: 342,
    availableQuantity: 342,
    checkedOutQuantity: 0,
    lowStockThreshold: 10,
    photoUrl: '/images/products/wireless-headphones.jpg',
    categoryId: 'audio-id',
    categoryName: 'Audio',
    createdOn: '2024-01-01T00:00:00Z',
    lastModifiedOn: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Smart Watch Pro',
    description: 'Fitness tracking device',
    sku: 'SW-1923',
    category: 'Wearables',
    stock: 18,
    status: 'Low Stock',
    image: '/images/products/smart-watch-pro.jpg',
    totalQuantity: 18,
    availableQuantity: 18,
    checkedOutQuantity: 0,
    lowStockThreshold: 10,
    photoUrl: '/images/products/smart-watch-pro.jpg',
    categoryId: 'wearables-id',
    categoryName: 'Wearables',
    createdOn: '2024-01-01T00:00:00Z',
    lastModifiedOn: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'Designer Sunglasses',
    description: 'UV protection eyewear',
    sku: 'SG-4521',
    category: 'Fashion',
    stock: 156,
    status: 'In Stock',
    image: '/images/products/designer-sunglasses.jpg',
    totalQuantity: 156,
    availableQuantity: 156,
    checkedOutQuantity: 0,
    lowStockThreshold: 10,
    photoUrl: '/images/products/designer-sunglasses.jpg',
    categoryId: 'fashion-id',
    categoryName: 'Fashion',
    createdOn: '2024-01-01T00:00:00Z',
    lastModifiedOn: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    name: 'Running Shoes',
    description: 'Athletic footwear',
    sku: 'RS-7834',
    category: 'Sports',
    stock: 89,
    status: 'Medium',
    image: '/images/products/running-shoes.jpg',
    totalQuantity: 89,
    availableQuantity: 89,
    checkedOutQuantity: 0,
    lowStockThreshold: 10,
    photoUrl: '/images/products/running-shoes.jpg',
    categoryId: 'sports-id',
    categoryName: 'Sports',
    createdOn: '2024-01-01T00:00:00Z',
    lastModifiedOn: '2024-01-01T00:00:00Z',
  },
  {
    id: '5',
    name: 'Leather Sneakers',
    description: 'Casual footwear',
    sku: 'LS-9012',
    category: 'Fashion',
    stock: 234,
    status: 'In Stock',
    image: '/images/products/leather-sneakers.jpg',
    totalQuantity: 234,
    availableQuantity: 234,
    checkedOutQuantity: 0,
    lowStockThreshold: 10,
    photoUrl: '/images/products/leather-sneakers.jpg',
    categoryId: 'fashion-id',
    categoryName: 'Fashion',
    createdOn: '2024-01-01T00:00:00Z',
    lastModifiedOn: '2024-01-01T00:00:00Z',
  },
  {
    id: '6',
    name: 'Smart Speaker',
    description: 'Voice assistant device',
    sku: 'SS-3456',
    category: 'Electronics',
    stock: 0,
    status: 'Out of Stock',
    image: '/images/products/smart-speaker.jpg',
    totalQuantity: 0,
    availableQuantity: 0,
    checkedOutQuantity: 0,
    lowStockThreshold: 10,
    photoUrl: '/images/products/smart-speaker.jpg',
    categoryId: 'electronics-id',
    categoryName: 'Electronics',
    createdOn: '2024-01-01T00:00:00Z',
    lastModifiedOn: '2024-01-01T00:00:00Z',
  },
  {
    id: '7',
    name: 'Backpack Pro',
    description: 'Travel backpack',
    sku: 'BP-6789',
    category: 'Accessories',
    stock: 412,
    status: 'In Stock',
    image: '/images/products/backpack-pro.jpg',
    totalQuantity: 412,
    availableQuantity: 412,
    checkedOutQuantity: 0,
    lowStockThreshold: 10,
    photoUrl: '/images/products/backpack-pro.jpg',
    categoryId: 'accessories-id',
    categoryName: 'Accessories',
    createdOn: '2024-01-01T00:00:00Z',
    lastModifiedOn: '2024-01-01T00:00:00Z',
  },
  {
    id: '8',
    name: 'Gaming Mouse',
    description: 'RGB gaming peripheral',
    sku: 'GM-2341',
    category: 'Gaming',
    stock: 267,
    status: 'In Stock',
    image: '/images/products/gaming-mouse.jpg',
    totalQuantity: 267,
    availableQuantity: 267,
    checkedOutQuantity: 0,
    lowStockThreshold: 10,
    photoUrl: '/images/products/gaming-mouse.jpg',
    categoryId: 'gaming-id',
    categoryName: 'Gaming',
    createdOn: '2024-01-01T00:00:00Z',
    lastModifiedOn: '2024-01-01T00:00:00Z',
  },
  {
    id: '9',
    name: 'Notebook Set',
    description: 'Premium stationery',
    sku: 'NB-5678',
    category: 'Stationery',
    stock: 12,
    status: 'Low Stock',
    image: '/images/products/notebook-set.jpg',
    totalQuantity: 12,
    availableQuantity: 12,
    checkedOutQuantity: 0,
    lowStockThreshold: 10,
    photoUrl: '/images/products/notebook-set.jpg',
    categoryId: 'stationery-id',
    categoryName: 'Stationery',
    createdOn: '2024-01-01T00:00:00Z',
    lastModifiedOn: '2024-01-01T00:00:00Z',
  },
  {
    id: '10',
    name: 'Water Bottle',
    description: 'Insulated bottle',
    sku: 'WB-8901',
    category: 'Sports',
    stock: 523,
    status: 'In Stock',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=200&h=200&fit=crop',
    totalQuantity: 523,
    availableQuantity: 523,
    checkedOutQuantity: 0,
    lowStockThreshold: 10,
    photoUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=200&h=200&fit=crop',
    categoryId: 'sports-id',
    categoryName: 'Sports',
    createdOn: '2024-01-01T00:00:00Z',
    lastModifiedOn: '2024-01-01T00:00:00Z',
  },
];

// Format stock quantity with units
export const formatStockQuantity = (quantity: number): string => {
  return `${quantity} units`;
};

// Format page range text
export const formatPageRange = (start: number, end: number, total: number): string => {
  return `Showing ${start} of ${total} products`;
};

// Format large numbers with commas
export const formatNumber = (num: number): string => {
  return num.toLocaleString();
};